Algoritmo "dobro_e_terca_parte"
// Calcula e exibe o dobro e a terça parte de um número real
Var
   numero, dobro, terca_parte : real

Inicio
   // Entrada de dados
   escreva("Digite um número: ")
   leia(numero)
   
   // Cálculos
   dobro <- numero * 2

   terca_parte <- numero / 3

   // Saída do resultado
   escreva("O dobro do número digitado é: ", dobro, " e a sua terça parte é: ", terca_parte:2:2)
Fimalgoritmo
