Algoritmo "soma_dois_numeros"
// Programa que lê dois números inteiros e exibe a soma entre eles
Var
   numero1, numero2, soma : inteiro

Inicio
   // Entrada de dados
   escreva("Digite o primeiro número: ")
   leia(numero1)

   escreva("Digite o segundo número: ")
   leia(numero2)

   // Cálculo
   soma <- numero1 + numero2

   // Saída do resultado
   escreva("A soma de ", numero1, " +", numero2, " resulta em",soma)
Fimalgoritmo
