Algoritmo "contagem_regressiva"
// Mostra na tela a contagem regressiva: 10 9 8 7 6 5 4 3 Acabou!
Var
   contagem : inteiro

Inicio
   // Inicializa a variável
   contagem <- 10

   // Realiza a contagem regressiva
   enquanto (contagem >= 3) faca
      escreva(contagem, " ")
      contagem <- contagem - 1
   fimenquanto

   // Mensagem de finalização
   escreva("Acabou")
Fimalgoritmo