Algoritmo "contagem"
// Programa que mostra a contagem de 6 a 11 e exibe "Acabou!" no final
Var
   contagem : inteiro
Inicio
   // Inicializa a variável para a contagem
   numero <- 6

   // Loop para realizar a contagem
   enquanto (contagem <= 11) faca
      contagem <- contagem + 1
      escreva(numero, " ") // Mostra o número na mesma linha, separado por espaço
   fimenquanto

   // Saída do resultado
   escreval("Acabou")
Fimalgoritmo